services:
  database:
    image: mysql:8.0
    container_name: wedding-mysql
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/wedding_rsvp_db_root_password
      MYSQL_DATABASE: wedding
      MYSQL_USER_FILE: /run/secrets/wedding_rsvp_db_user
      MYSQL_PASSWORD_FILE: /run/secrets/wedding_rsvp_db_password
    ports:
      - "3306:3306"
    networks:
      - mynetwork
    secrets:
      - wedding_rsvp_db_root_password
      - wedding_rsvp_db_password
      - wedding_rsvp_db_user

  wedding-rsvp-beef:
    # Use with `docker stack deploy -c docker-compose.yaml wedding`.
    # Build first with `docker-compose build`. Uncomment the build section to build the image.
    #image: z5116890/wedding-rsvp-wedding-rsvp-beef:latest
    image: z5116890/wedding-rsvp-beef-local:latest
    # build:
    #   context: ./components/wedding-rsvp-beef
    environment:
      MYSQL_DATABASE: wedding
      MYSQL_USER_FILE: /run/secrets/wedding_rsvp_db_user
      MYSQL_PASSWORD_FILE: /run/secrets/wedding_rsvp_db_password
      MYSQL_HOST: database
    ports:
      - "3000:3000"
    secrets:
      - wedding_rsvp_db_user
      - wedding_rsvp_db_password
    depends_on:
      - database
    networks:
      - mynetwork
  # wedding-rsvp:
  #   image: nginx:latest
  #   container_name: wedding-rsvp
  #   volumes:
  #     - ./frontend:/usr/share/nginx/html  # Point to the build folder
  #     - ./nginx.conf:/etc/nginx/conf.d/default.conf  # Custom Nginx config

  #   ports:
  #     - "80:80"
  #   networks:
  #     - mynetwork
  #   depends_on:
  #     - wedding-rsvp-beef

volumes:
  db_data:

networks:
  mynetwork:
    driver: overlay

secrets:
  wedding_rsvp_db_root_password:
    external: true
  wedding_rsvp_db_password:
    external: true
  wedding_rsvp_db_user:
    external: true
